### PR TITLE
Fixes issue #8

### PR DESCRIPTION
**Pull request by knrz**
To be honest, the functions in the math and statistics directories are way over my head, and I don't know if they should return nil if passed an empty list.

I also did some cleaning up :shipit:

### CODE REVIEW

**Comment by msharp** [comment]
Thank @knrz that looks very helpful.

Can you also add test cases for all the new function heads? (in ./test/descriptive_test.exs)

**Comment by knrz** [comment]
Bump :facepunch:

**Comment by msharp** [comment]
The changes  look fine. I'm away on holiday at the moment with limited internet access. I'll be back home next week and I can review the changes properly.

**Comment by knrz** [comment]
Sounds good :smiley: :shipit:

**Pull request merged**
